# Generated by Django 2.1.4 on 2018-12-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0003_auto_20181217_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=None, on_delete=True, to='bookinfo.Publisher'),
        ),
    ]
