# Generated by Django 2.1.4 on 2018-12-17 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0004_auto_20181217_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bookinfo.Publisher'),
        ),
    ]
